---
- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
    state: latest

- name: deploy vhosts
  template:
    src: "nginx_vhost.conf.j2"
    dest: "/etc/nginx/sites-enabled/default"
    owner: "www-data"
    group: "www-data"
    mode: 0600
  notify: Reload nginx
