---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  strategy: linear
  pre_tasks:
    - name: Loading groups variables
      no_log: false
      include_vars:
        file: "group_vars/all.yml"
      ignore_errors: true
  roles:
    - role: users
      ops_users:
        - name: mikrob
          ssh_key_pub: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAtfWGk8lSEIbwvXSBvK8osch/eU7Uwdq5GsXOihKM5OsxN0VTrmVYro/eL/2fwdTlbgOxYF8bMlgY8EA/IngzxwmMfUpTk2mZ1p6+ScgQI6EVOM4YVvNEcaI2ZvXhnJxm21XQX1Aeh4EwcXac/e6FyT/f32TG+V5eQdE+VhE7iIVxCF/wCUBPDcRnRsbohNRDcaJ8kIM6+rflwU5XozaAOIow8Y/kDDzKZVEBK9LulY9HskLaiuxxI72XW5DnAzoAcbkmw3df9Ve21qFtXY6+ClKfnc2pL+HnrgjPtWa6P/gghEByXsDVFCARu69g3CYrweCsDrSgWU50EsvthxSdZQ== octo-mro@octo-mro-laptop
        - name: devops
          ssh_key_pub: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAtfWGk8lSEIbwvXSBvK8osch/eU7Uwdq5GsXOihKM5OsxN0VTrmVYro/eL/2fwdTlbgOxYF8bMlgY8EA/IngzxwmMfUpTk2mZ1p6+ScgQI6EVOM4YVvNEcaI2ZvXhnJxm21XQX1Aeh4EwcXac/e6FyT/f32TG+V5eQdE+VhE7iIVxCF/wCUBPDcRnRsbohNRDcaJ8kIM6+rflwU5XozaAOIow8Y/kDDzKZVEBK9LulY9HskLaiuxxI72XW5DnAzoAcbkmw3df9Ve21qFtXY6+ClKfnc2pL+HnrgjPtWa6P/gghEByXsDVFCARu69g3CYrweCsDrSgWU50EsvthxSdZQ== octo-mro@octo-mro-laptop
    - role: base

- hosts: bdd
  become: true
  become_method: sudo
  become_user: root
  strategy: linear
  roles:
    - role: mysql

- hosts: front
  become: true
  become_method: sudo
  become_user: root
  strategy: linear
  roles:
    - role: nginx

- hosts: app
  become: true
  become_method: sudo
  become_user: root
  strategy: linear
  roles:
    - role: rails
